### ISSUE TITLE
Expose alpha state in registry documentation

### ISSUE THREAD

**Issue by toddfarmer** [redpanda-data/terraform-provider-redpanda#111]
The [GitHub repo readme](https://github.com/redpanda-data/terraform-provider-redpanda?tab=readme-ov-file#readme) explicitly states this is in an alpha state, but that is not exposed in registry documentation. It would be useful to surface this information there - it may not be common for users to visit the repo.

**Comment by gene-redpanda** [comment]
https://github.com/redpanda-data/terraform-provider-redpanda/pull/110
