### ISSUE TITLE
cache access token for the cloud token. 

### ISSUE THREAD

**Issue by sago2k8** [redpanda-data/terraform-provider-redpanda#155]
Store JWT access token instead of requesting it for every request. 

We have encountered that the terraform client is requesting multiple access tokens when calling the public-api, A possible solution would be to store the token and only request a new one when its about to expire.

**Comment by ligfx** [comment]
@sago2k8 #157 should help. You can now pass in a token directly instead of a client ID and secret, which gives you the ability to request and cache the token outside of Terraform.

**Comment by david-yu** [comment]
@sago2k8 Could we close this issue now that #157 is merged?

**Comment by sago2k8** [comment]
I think so, closing now, I think we should maybe communicate to the customer so they start using it.
