### ISSUE TITLE
Improved error messages for validating cluster names upon creation 

### ISSUE THREAD

**Issue by mjroeleveld** [redpanda-data/terraform-provider-redpanda#181]
The following results in an RPC error NotFound.

```
resource "redpanda_resource_group" "main" {
  name = "main"
}

resource "redpanda_serverless_cluster" "main" {
  name              = "main"
  resource_group_id = redpanda_resource_group.main.id
  serverless_region = "eu-central-1"
}
```

```
 Error: failed to create serverless cluster
│
│   with module.redpanda.redpanda_serverless_cluster.main,
│   on ../../modules/redpanda/cluster.tf line 5, in resource "redpanda_serverless_cluster" "main":
│    5: resource "redpanda_serverless_cluster" "main" {
│
│ rpc error: code = NotFound desc =
```

**Comment by david-yu** [comment]
Hi @mjroeleveld we don't have great error messages yet in our TF Provider but the main issue here if you also test this out on the Cloud UI is that there is a 6 character minimum for cluster names.

**Comment by mjroeleveld** [comment]
@david-yu unfortunately I still get the error with e.g. `verylongname`

**Comment by mjroeleveld** [comment]
Apparently, the region had to be prefixed with `pro-`.

**Comment by sago2k8** [comment]
The problem is the region indeed, I'll bring it up so the api returns a better error message.

**Comment by sago2k8** [comment]
correct region name is `pro-eu-central-1`
